-- CaseSmith schema 範例(DB2 方言)。
-- 給使用者的 ddl2json.mjs parser 當參考輸入,對應 schema.example.json。
-- 表名/欄名一律通用假名,非任何真實系統。

CREATE TABLE APP.T_CUSTOMER (
    CUST_ID     DECIMAL(10,0) NOT NULL,
    CUST_NM     VARCHAR(60)   NOT NULL,
    COUNTRY_CD  CHAR(2),
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE APP.T_PRODUCT (
    PRODUCT_ID  DECIMAL(10,0) NOT NULL,
    PRODUCT_NM  VARCHAR(80)   NOT NULL,
    UNIT_PRICE  DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE APP.T_ORDER (
    ORDER_ID    DECIMAL(10,0) NOT NULL,
    CUST_ID     DECIMAL(10,0) NOT NULL,
    STATUS_CD   CHAR(1)       NOT NULL,
    ORDER_DT    DATE,
    PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_CUST FOREIGN KEY (CUST_ID)
        REFERENCES APP.T_CUSTOMER (CUST_ID)
);

CREATE TABLE APP.T_ORDER_ITEM (
    ORDER_ITEM_ID DECIMAL(10,0) NOT NULL,
    ORDER_ID      DECIMAL(10,0) NOT NULL,
    PRODUCT_ID    DECIMAL(10,0) NOT NULL,
    QTY           INTEGER       NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ITEM_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES APP.T_ORDER (ORDER_ID),
    CONSTRAINT FK_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES APP.T_PRODUCT (PRODUCT_ID)
);

-- 兩表互指的 FK 環示範:ACCOUNT.PROFILE_ID 可為 NULL,是環打斷點;
-- PROFILE.ACCOUNT_ID NOT NULL,不能作為打斷點。
CREATE TABLE APP.T_ACCOUNT (
    ACCOUNT_ID  DECIMAL(10,0) NOT NULL,
    PROFILE_ID  DECIMAL(10,0),
    LOGIN_NM    VARCHAR(30)   NOT NULL,
    PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE APP.T_PROFILE (
    PROFILE_ID  DECIMAL(10,0) NOT NULL,
    ACCOUNT_ID  DECIMAL(10,0) NOT NULL,
    DISPLAY_NM  VARCHAR(40),
    PRIMARY KEY (PROFILE_ID),
    CONSTRAINT FK_PROFILE_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
        REFERENCES APP.T_ACCOUNT (ACCOUNT_ID)
);

ALTER TABLE APP.T_ACCOUNT
    ADD CONSTRAINT FK_ACCOUNT_PROFILE FOREIGN KEY (PROFILE_ID)
    REFERENCES APP.T_PROFILE (PROFILE_ID);
